language: node_js
node_js:
  - "8.11.2"
branches:
  only:
    - master
    - plugin
before_script:
  - yarn install
  - yarn global add typescript
script:
  - yarn run build
  - yarn run test
after_success:
  - yarn run coverage
